global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - "mariadb_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'mariadb'
    static_configs:
    - targets: ['mysqld-exporter:9104']
  - job_name: 'node-exporter'
    static_configs:
    - targets: ['host.docker.internal:9100']
