---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: traefik-ingress-controller
  namespace: traefik
  labels:
    k8s-app: traefik-ingress-lb
spec:
  selector:
   matchLabels:
     name: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      #minikube
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - image: traefik:v2.5
        name: traefik-ingress-lb
        #no ports with hostNetwork
        # ports:
        # - name: http
        #   containerPort: 80
        #   hostPort: 80
        # - name: admin
        #   containerPort: 8080
        #   hostPort: 8080
        securityContext:
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
        args:
        - --api
        - --api.debug=false
        - --api.dashboard=true
        - --api.insecure=true
        - --ping
        - --entrypoints.web.address=:80
        - --entrypoints.web.forwardedheaders.insecure=true
        - --providers.kubernetescrd=true
        - --providers.kubernetesingress=true
        - --serverstransport.insecureskipverify=true
        - --global.sendanonymoususage=false
        - --accesslog
        - --log.level=INFO
        livenessProbe:
          httpGet:
            path: /ping
            port: 8080
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
