---
apiVersion: v1
kind: Service
metadata:
 name: traefik-web-ui
 namespace: traefik
spec:
 selector:
   k8s-app: traefik-ingress-lb
   app: traefik-ingress-lb
 ports:
 - port: 8080
   targetPort: 8080
   name: api
 - port: 80
   targetPort: 80
   name: web

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: traefik
  labels:
    app: traefik
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`traefik.127.0.0.1.nip.io`)
    kind: Rule
    services:
    # - name: traefik-web-ui
    #   port: 8080
    - name: api@internal
      kind: TraefikService
