version: '3.1'

networks:
  default:
   name: mariadb

services:
  mariadb:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: demo
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb:/docker-entrypoint-initdb.d/


  prometheus:
    image: prom/prometheus:latest
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=12d'
    volumes:
      - ./prometheus/config/:/etc/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 9090:9090


  node_exporter:
    image: quay.io/prometheus/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host/rootfs:ro,rslave
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      - '--web.listen-address=0.0.0.0:9100'
    network_mode: host


  mysqld-exporter:
    image: prom/mysqld-exporter
    environment:
      DATA_SOURCE_NAME: exporter:exporter@(mariadb:3306)/
    ports:
      - "9104:9104"
    command:
    # default on:
    - "--collect.global_status"
    - "--collect.global_variables"
    - "--collect.slave_status"
    - "--collect.info_schema.innodb_cmp"
    - "--collect.info_schema.innodb_cmpmem"
    - "--collect.info_schema.query_response_time"
    # added
    - "--collect.info_schema.clientstats"
    - "--collect.perf_schema.eventswaits"
    - "--collect.perf_schema.file_instances"
      
  grafana:
    image: grafana/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/

  # alertmanager:
  #   image: prom/alertmanager
  #   ports:
  #     - "9093:9093"
  #   restart: on-failure
  #   volumes:
  #     - ./alertmanager/config:/etc/alertmanager

  adminer:
    image: adminer
    environment:
      ADMINER_DEFAULT_DB_HOST: mariadb
      ADMINER_DEFAULT_DB_NAME: demo
    ports:
      - "8080:8080"
